version: '3.4'

services:
  lighthouse:
    image: petabridge/lighthouse:v0.9.2
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "webcrawler"
      CLUSTER_IP: lighthouse
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"

  filehandler:
    image: dpires/filehandler
    build:
      context: .
      dockerfile: DIAssignment.FileHandler/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: filehandler
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"

  esentrypoint:
    image: dpires/esentrypoint
    build:
      context: .
      dockerfile: DIAssignment.ESEntryPoint/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: esentrypoint
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"


  eventstore:
    image: dpires/eventstore
    build:
      context: .
      dockerfile: DIAssignment.EventStore/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: eventstore
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"


  projection:
    image: dpires/projection
    build:
      context: .
      dockerfile: DIAssignment.Projection/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://webcrawler@lighthouse:4053"
      CLUSTER_IP: projection
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"

