version: '3.4'

services:
  lighthouse:
    image: petabridge/lighthouse:v0.9.2
    restart: unless-stopped
    environment:
      ACTORSYSTEM: "dia"
      CLUSTER_IP: lighthouse
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://dia@lighthouse:4053"

  filehandler:
    image: dpires/filehandler
    restart: unless-stopped
    build:
      context: .
      dockerfile: DIAssignment.FileHandler/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://dia@lighthouse:4053"
      CLUSTER_IP: filehandler
      CLUSTER_PORT: 0
    depends_on:
      - "lighthouse"

  esentrypoint:
    image: dpires/esentrypoint
    restart: unless-stopped
    build:
      context: .
      dockerfile: DIAssignment.ESEntryPoint/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://dia@lighthouse:4053"
      CLUSTER_IP: esentrypoint
      CLUSTER_PORT: 0
      ELASTIC_URL: "http://elastic:9200"
    depends_on:
      - "lighthouse"
      - "elastic"


  eventstore:
    image: dpires/eventstore
    restart: unless-stopped
    build:
      context: .
      dockerfile: DIAssignment.EventStore/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://dia@lighthouse:4053"
      CLUSTER_IP: eventstore
      CLUSTER_PORT: 0
      MONGO_USER: mongo
      MONGO_PASS: mongo
      MONGO_DB: events
    depends_on:
      - "lighthouse"
      - "mongo"


  projection:
    image: dpires/projection
    restart: unless-stopped
    build:
      context: .
      dockerfile: DIAssignment.Projection/Dockerfile
    environment:
      CLUSTER_SEEDS: "akka.tcp://dia@lighthouse:4053"
      CLUSTER_IP: projection
      CLUSTER_PORT: 0
      MONGO_USER: mongo
      MONGO_PASS: mongo
      MONGO_DB_EVENTS: events
      MONGO_DB_PROJECTION: projections
    depends_on:
      - "lighthouse"
      - "mongo"

  mongo:
    image: dpires/mongo
    restart: unless-stopped
    build:
      context: Mongo/
    #volumes:
    #  - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: admin

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    depends_on:
      - "elastic"

#volumes:
#  mongo-data: {}
#  elastic-data: {}
